// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xovauswynufszcukmsas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvdmF1c3d5bnVmc3pjdWttc2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDU2OTgsImV4cCI6MjA1OTI4MTY5OH0.Aq9O8V7WCEtblGOFBTYfG3zVjlY7210B_9S7jkudDH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);